steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build' '-t', 'australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/my-app:S{SHORT_SHA}', '.']

  # Docker Push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push' '-t', 'australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/my-app:S{SHORT_SHA}']

# Store images in Google Artifact Registry
images:
  - australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/my-app:S{SHORT_SHA}