steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/spring-boot:$SHORT_SHA', '.']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spring-boot'
      - '--image'
      - 'australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/spring-boot:$SHORT_SHA'
      - '--region'
      - 'australia-southeast2'
      - '--allow-unauthenticated'
images: ['australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/spring-boot:$SHORT_SHA']