steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/spring-boot', '.']
images: ['australia-southeast2-docker.pkg.dev/imposing-volt-418217/cloudbuild-repo/spring-boot']